version: '3'

services:
  hpopt_notebook:
    image: hpopt:spark-3.0.1
    build:
      context: .
      args:
        - BASE_CONTAINER=jupyter/all-spark-notebook:703d8b2dcb88
    volumes:
      - ./notebooks_from_container:/home/jovyan/hpopt_notebooks
    ports:
      - '8888:8888'
      - '4040:4040'
      - '4041:4041'
      - '4042:4042'